// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApp.Api.Data;

#nullable disable

namespace RecipeApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618014523_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.ConfirmedIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FridgeScanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FridgeScanId");

                    b.ToTable("ConfirmedIngredients");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.DetectedIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FridgeScanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NeedsConfirmation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuantityVisible")
                        .HasColumnType("longtext");

                    b.Property<int?>("SourceImageIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeScanId");

                    b.ToTable("DetectedIngredients");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.DeviceUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceUsers");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.ExternalApiCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CostUnits")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeviceUserId")
                        .HasColumnType("char(36)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ExternalApiCallLogs");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.FridgeScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("ImageCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUserId");

                    b.ToTable("FridgeScans");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.RecipeInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SpoonacularRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUserId");

                    b.ToTable("RecipeInteractions");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.RecipeSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FridgeScanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUserId");

                    b.ToTable("RecipeSearches");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.SavedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SpoonacularRecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUserId");

                    b.ToTable("SavedRecipes");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.ScanImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FridgeScanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FridgeScanId");

                    b.ToTable("ScanImages");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.UsageCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("DeviceUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RecipeDetailsUsed")
                        .HasColumnType("int");

                    b.Property<int>("RecipeSearchesUsed")
                        .HasColumnType("int");

                    b.Property<int>("ScansUsed")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUserId", "DateUtc")
                        .IsUnique();

                    b.ToTable("UsageCounters");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.ConfirmedIngredient", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.FridgeScan", "FridgeScan")
                        .WithMany("ConfirmedIngredients")
                        .HasForeignKey("FridgeScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeScan");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.DetectedIngredient", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.FridgeScan", "FridgeScan")
                        .WithMany("DetectedIngredients")
                        .HasForeignKey("FridgeScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeScan");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.FridgeScan", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.DeviceUser", "DeviceUser")
                        .WithMany("Scans")
                        .HasForeignKey("DeviceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceUser");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.RecipeInteraction", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.DeviceUser", "DeviceUser")
                        .WithMany("Interactions")
                        .HasForeignKey("DeviceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceUser");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.RecipeSearch", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.DeviceUser", "DeviceUser")
                        .WithMany("RecipeSearches")
                        .HasForeignKey("DeviceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceUser");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.SavedRecipe", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.DeviceUser", "DeviceUser")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("DeviceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceUser");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.ScanImage", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.FridgeScan", "FridgeScan")
                        .WithMany("Images")
                        .HasForeignKey("FridgeScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeScan");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.UsageCounter", b =>
                {
                    b.HasOne("RecipeApp.Api.Data.Entities.DeviceUser", "DeviceUser")
                        .WithMany("UsageCounters")
                        .HasForeignKey("DeviceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceUser");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.DeviceUser", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("RecipeSearches");

                    b.Navigation("SavedRecipes");

                    b.Navigation("Scans");

                    b.Navigation("UsageCounters");
                });

            modelBuilder.Entity("RecipeApp.Api.Data.Entities.FridgeScan", b =>
                {
                    b.Navigation("ConfirmedIngredients");

                    b.Navigation("DetectedIngredients");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
